const RESENT_ORDERS_data = [
  {
    id: "1",
    product_id: "5434",
    customer_id: "15",
    customer_name: "Hamid Azimi",
    order_date: "2024-10-06T12:22:02",
    order_total: "$356.00",
    current_order_status: "SHIPPED",
    shipment_address: "iran tehran enghelab.",
  },
  {
    id: "2",
    product_id: "6532",
    customer_id: "23",
    customer_name: "Sara Mohammadi",
    order_date: "2024-09-29T09:11:22",
    order_total: "$180.00",
    current_order_status: "DELIVERED",
    shipment_address: "iran shiraz zand st.",
  },
  {
    id: "3",
    product_id: "7765",
    customer_id: "34",
    customer_name: "Ali Rezaei",
    order_date: "2024-09-20T14:45:09",
    order_total: "$475.00",
    current_order_status: "OUT_OF_DELIVERY",
    shipment_address: "iran isfahan naqsh-e jahan.",
  },
  {
    id: "4",
    product_id: "3241",
    customer_id: "45",
    customer_name: "Maryam Kiani",
    order_date: "2024-10-01T10:15:34",
    order_total: "$220.00",
    current_order_status: "PLACED",
    shipment_address: "iran mashhad imam reza st.",
  },
  {
    id: "5",
    product_id: "9872",
    customer_id: "56",
    customer_name: "Reza Soltani",
    order_date: "2024-10-03T16:22:12",
    order_total: "$310.00",
    current_order_status: "SHIPPED",
    shipment_address: "iran tabriz shahid beheshti st.",
  },
  {
    id: "6",
    product_id: "4412",
    customer_id: "78",
    customer_name: "Farideh Hosseini",
    order_date: "2024-09-18T11:45:56",
    order_total: "$520.00",
    current_order_status: "CONFIRMED",
    shipment_address: "iran kerman jomhouri ave.",
  },
  {
    id: "7",
    product_id: "8934",
    customer_id: "89",
    customer_name: "Mohammad Karimi",
    order_date: "2024-10-04T08:33:19",
    order_total: "$430.00",
    current_order_status: "DELIVERED",
    shipment_address: "iran yazd saadi st.",
  },
  {
    id: "8",
    product_id: "5543",
    customer_id: "90",
    customer_name: "Neda Rahmani",
    order_date: "2024-09-30T07:25:45",
    order_total: "$265.00",
    current_order_status: "PLACED",
    shipment_address: "iran ahvaz azadi st.",
  },
  {
    id: "9",
    product_id: "6271",
    customer_id: "61",
    customer_name: "Hassan Ghasemi",
    order_date: "2024-10-05T15:12:07",
    order_total: "$395.00",
    current_order_status: "SHIPPED",
    shipment_address: "iran esfahan sheikh bahaei st.",
  },
  {
    id: "10",
    product_id: "7812",
    customer_id: "72",
    customer_name: "Leila Mehrabi",
    order_date: "2024-10-02T17:14:36",
    order_total: "$385.00",
    current_order_status: "OUT_OF_DELIVERY",
    shipment_address: "iran tehran pasdaran st.",
  },
];

export { RESENT_ORDERS_data };
